# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Wöhrl, Developer & Artist
email: hey@benjaminwoehrl.de
description: > # Ist Mitgründer der Pixelrowdies und seit über 5 Jahren selbständiger Entwickler und Designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: /:title/


# Build settings
markdown: kramdown
